# -*- python -*-

Import("env")
env = env.Clone()

sources = [
    "layout1.cpp",
    "hello.cpp",
    "stream1.cpp",
    "input.cpp",
    "input2.cpp",
    "list.cpp"
]

examples = []

for s in sources :
    examples.append(env.Program(target = s[:-4], source = [s], LIBS = ["cwpp"], LIBPATH = "../"))

Alias("examples", examples)
