# -*- python -*-

Import("env")
env = env.Clone()

env.Program(
    target = "layout1",
    source = ["layout1.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)

env.Program(
    target = "hello",
    source = ["hello.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)

env.Program(
    target = "stream1",
    source = ["stream1.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)

env.Program(
    target = "input",
    source = ["input.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)

env.Program(
    target = "input2",
    source = ["input2.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)
