# -*- python -*-

Import("env")
env = env.Clone()

env.Program(
    target = "layout1",
    source = ["layout1.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)

env.Program(
    target = "hello",
    source = ["hello.cpp"],
    LIBS = ["cwpp"],
    LIBPATH = "../"
)
